function [BW,maskedRGBImage] = BottomBuilding(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 03-Apr-2016
%------------------------------------------------------


% Convert RGB image to chosen color space
I = rgb2ycbcr(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 120.000/255;
channel1Max = 148.000/255;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 56.000/255;
channel2Max = 159.000/255;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 80.000/255;
channel3Max = 183.000/255;

% Create mask based on chosen histogram thresholds
BW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);

% ED = sqrt(((I(:,:,1)-mean([channel1Max,channel1Min])).^2 +...
%     (I(:,:,1)-mean([channel1Max,channel1Min])).^2 +...
%     (I(:,:,1)-mean([channel1Max,channel1Min])).^2)/3);
% 
% ED(BW) = 1;
% BW = ED;

% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;
